"""Tests for task 0158: per-role codex homes generated by ``greatminds setup``.

codex 0.130.0 removed the per-role-file mechanism that ``greatminds``
relied on (``~/.codex/<role>.config.toml``). The current ``--profile``
flag reads ``[profiles.<role>]`` from ``$CODEX_HOME/config.toml`` only.
0158 generates per-role ``$CODEX_HOME`` dirs at
``<project>/coordination/.codex-home/<role>/`` at setup time, and
``start_agent.py`` points codex at that dir via the ``CODEX_HOME`` env.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from greatminds.cli import setup as setup_mod


def _make_canon_with_profiles(canon_root: Path, role_payloads: dict[str, str]) -> None:
    """Lay down a fake canon profiles dir with one .config.toml per role."""
    pdir = canon_root / "codex" / "profiles"
    pdir.mkdir(parents=True)
    for role, body in role_payloads.items():
        (pdir / f"{role}.config.toml").write_text(body, encoding="utf-8")


# ---------- generation ----------


def test_setup_creates_one_codex_home_per_role(tmp_path: Path) -> None:
    """One ``<role>/config.toml`` per shipped profile gets written under
    ``coordination/.codex-home/``."""
    canon = tmp_path / "canon"
    project = tmp_path / "project"
    project.mkdir()
    _make_canon_with_profiles(canon, {
        "developer": 'developer_instructions = "x"\n[profiles.developer]\nmodel="gpt-5"\n',
        "tester":    'developer_instructions = "y"\n[profiles.tester]\nmodel="gpt-5"\n',
    })

    written, skipped = setup_mod._setup_codex_homes_per_role(canon, project)
    assert written == 2
    assert skipped == 0
    for role in ("developer", "tester"):
        cfg = project / "coordination" / ".codex-home" / role / "config.toml"
        assert cfg.is_file(), f"missing {cfg}"


def test_generated_config_has_top_level_developer_instructions(tmp_path: Path) -> None:
    """Round-trip: the shipped file's top-level ``developer_instructions``
    key must survive into the generated home untouched. codex 0.130
    silently drops profile-scoped ``developer_instructions``; only the
    top-level form is injected."""
    canon = tmp_path / "canon"
    project = tmp_path / "project"
    project.mkdir()
    body = (
        'developer_instructions = """role intro"""\n\n'
        '[profiles.developer]\nmodel = "gpt-5"\n'
    )
    _make_canon_with_profiles(canon, {"developer": body})

    setup_mod._setup_codex_homes_per_role(canon, project)

    cfg = project / "coordination" / ".codex-home" / "developer" / "config.toml"
    text = cfg.read_text(encoding="utf-8")
    assert text.startswith("developer_instructions ="), text[:200]
    assert "[profiles.developer]" in text


def test_generated_config_has_profile_section(tmp_path: Path) -> None:
    """The generated config.toml carries ``[profiles.<role>]`` with the
    three required fields. ``codex --profile <role>`` errors when the
    section is missing (the fleet-blocker 0153 vintage)."""
    canon = tmp_path / "canon"
    project = tmp_path / "project"
    project.mkdir()
    body = (
        'developer_instructions = """ok"""\n\n'
        '[profiles.developer]\n'
        'model = "gpt-5"\n'
        'approval_policy = "never"\n'
        'sandbox_mode = "danger-full-access"\n'
    )
    _make_canon_with_profiles(canon, {"developer": body})

    setup_mod._setup_codex_homes_per_role(canon, project)

    text = (project / "coordination" / ".codex-home" / "developer"
            / "config.toml").read_text(encoding="utf-8")
    assert "[profiles.developer]" in text
    assert "model = " in text
    assert "approval_policy = " in text
    assert "sandbox_mode = " in text


# ---------- idempotency ----------


def test_setup_does_not_clobber_operator_edits(tmp_path: Path) -> None:
    """Re-running setup on an existing per-role home leaves operator
    edits intact. Per-project, per-role config is operator-owned after
    first write; subsequent setups preserve."""
    canon = tmp_path / "canon"
    project = tmp_path / "project"
    project.mkdir()
    _make_canon_with_profiles(canon, {
        "developer": 'developer_instructions = "shipped"\n',
    })

    setup_mod._setup_codex_homes_per_role(canon, project)
    cfg = project / "coordination" / ".codex-home" / "developer" / "config.toml"
    edited = 'developer_instructions = "operator-edited"\n# extra comment\n'
    cfg.write_text(edited, encoding="utf-8")

    written, skipped = setup_mod._setup_codex_homes_per_role(canon, project)
    assert written == 0
    assert skipped == 1
    assert cfg.read_text(encoding="utf-8") == edited, (
        "0158: operator edits to per-role config.toml must survive setup"
    )


def test_setup_returns_zeroes_when_no_profiles(tmp_path: Path) -> None:
    """Missing canon profiles dir → no-op, no crash. Defensive: a
    minimal canon (e.g. early dev install) might omit codex/."""
    canon = tmp_path / "canon-empty"
    canon.mkdir()
    project = tmp_path / "project"
    project.mkdir()

    written, skipped = setup_mod._setup_codex_homes_per_role(canon, project)
    assert written == 0
    assert skipped == 0


# ---------- shipped profile format ----------


def test_shipped_profiles_have_developer_instructions_key() -> None:
    """0158: shipped profiles under
    ``src/greatminds/data/codex/profiles/`` must declare
    ``developer_instructions`` at top level. Pre-0158 they used the
    ``instructions`` key, which codex 0.130 silently doesn't inject
    (the upstream API rename caught us mid-flight)."""
    canon_dir = Path(__file__).resolve().parents[2] / "src" / "greatminds" / "data"
    profiles = canon_dir / "codex" / "profiles"
    for f in sorted(profiles.glob("*.config.toml")):
        text = f.read_text(encoding="utf-8")
        assert "developer_instructions = " in text, (
            f"0158: {f.name} must declare developer_instructions at top level "
            f"(pre-0158 'instructions' key is not read by codex 0.130+)"
        )
        # Negative pin: the obsolete top-level 'instructions = "' key must
        # not be present (otherwise both keys exist and codex picks neither).
        assert "\ninstructions = " not in text and not text.startswith("instructions = "), (
            f"0158: {f.name} still has stale 'instructions = ' key"
        )


def test_shipped_profiles_have_profile_section_with_required_fields() -> None:
    """0158: shipped profiles must declare ``[profiles.<role>]`` with
    ``model``, ``approval_policy``, ``sandbox_mode``. ``codex --profile
    <role>`` errors with ``config profile not found`` when the section
    is missing — the fleet-blocker we just dug out of in 0153 and now
    in 0158 is the same shape of bug."""
    canon_dir = Path(__file__).resolve().parents[2] / "src" / "greatminds" / "data"
    profiles = canon_dir / "codex" / "profiles"
    for f in sorted(profiles.glob("*.config.toml")):
        role = f.stem.replace(".config", "")
        text = f.read_text(encoding="utf-8")
        assert f"[profiles.{role}]" in text, (
            f"0158: {f.name} missing [profiles.{role}] section"
        )
        # Required fields under the section.
        for field in ("model", "approval_policy", "sandbox_mode"):
            assert f"{field} = " in text, (
                f"0158: {f.name} missing {field!r} in profile section"
            )
