"""Generate the checked-in mechanical reference from this checkout's contracts."""
import argparse
from dataclasses import MISSING, fields
import hashlib
import inspect
import json
import os
from pathlib import Path

import yaml

from greatminds.core.schema import load_schema_snapshot
from greatminds.runtime import config, store, account_limits, presets


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs/architecture/contract-reference.md'


def validate(document):
    from greatminds.cli.task import SCHEMA_REQUIRES_VALIDATORS
    roles, queues = document['roles'], document['queues']
    if not isinstance(roles, dict) or not roles or not isinstance(queues, dict) or not queues:
        raise ValueError('roles and queues must be nonempty mappings')
    for name, role in roles.items():
        if role.get('lifecycle') not in {'interactive', 'driven'}:
            raise ValueError(f'unknown lifecycle for {name}')
        if set(role.get('claims_from', [])) - queues.keys():
            raise ValueError(f'unknown claim queue for {name}')
    for name, queue in queues.items():
        if queue.get('owner') is not None and queue['owner'] not in roles:
            raise ValueError(f'unknown owner for {name}')
        if set(queue.get('writers', [])) - roles.keys():
            raise ValueError(f'unknown writer for {name}')
    for transition in document['transitions']:
        if (transition['from'] not in set(queues) | {'any_active_queue'}
                or transition['to'] not in set(queues) | {'any_resume_to_queue'}
                or transition['by'] not in set(roles) | {'current_owner'}):
            raise ValueError('transition references an unknown role or queue')
        if set(transition.get('requires', [])) - SCHEMA_REQUIRES_VALIDATORS.keys():
            raise ValueError('transition references an unregistered requirement validator')
    known_states = set(store.TRANSITIONS) | store.TERMINAL
    if any(set(targets) - known_states for targets in store.TRANSITIONS.values()):
        raise ValueError('runtime transition references an unknown state')
    # Exercise every shipped roster through the actual execution validator.
    examples = {}
    for name, roster in sorted(presets.PRESETS.items()):
        example = {'version': 1, 'agents': {'configured-acp': {'transport': 'acp',
            'argv': ['replace-with-installed-acp-executable'], 'adapter_version': 'replace-with-tested-version',
            'harness_version': 'replace-with-tested-version'}},
            'bindings': {key: {'role': role, 'scheduling': scheduling, 'agent': 'configured-acp'}
                         for key, (role, scheduling) in roster.items()}}
        config.parse_execution_config(example, roles=set(roles))
        examples[name] = example
    return examples


def cell(value):
    text = value if isinstance(value, str) else json.dumps(value, sort_keys=True, ensure_ascii=True)
    return text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('|', '&#124;').replace('\n', '<br>')


def table(headers, rows):
    return ['| ' + ' | '.join(map(cell, headers)) + ' |',
            '| ' + ' | '.join('---' for _ in headers) + ' |',
            *['| ' + ' | '.join(map(cell, row)) + ' |' for row in rows], '']


def render():
    if os.environ.get('GREATMINDS_CANON_DIR'):
        raise ValueError('unset GREATMINDS_CANON_DIR when generating checkout documentation')
    snapshot = load_schema_snapshot(ROOT / 'src/greatminds/data')
    from importlib.resources import files
    if files('greatminds.data').joinpath('schema.yaml').read_bytes() != snapshot.text.encode():
        raise ValueError('installed schema differs from this checkout')
    document = snapshot.document
    examples = validate(document)
    from greatminds.cli import task
    from greatminds.domain import maintenance, results
    sources = {}
    for module in (config, store, account_limits, presets, task, maintenance, results):
        loaded = Path(inspect.getfile(module))
        relative = Path('src') / Path(*module.__name__.split('.')).with_suffix('.py')
        raw = (ROOT / relative).read_bytes()
        if loaded.read_bytes() != raw:
            raise ValueError(f'imported {module.__name__} differs from this checkout; install its current wheel or use its editable environment')
        sources[str(relative)] = hashlib.sha256(raw).hexdigest()
    sources['src/greatminds/data/schema.yaml'] = snapshot.sha256
    sources['tools/generate_contract_reference.py'] = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    lines = ['# Generated contract reference', '',
        'Generated by `python tools/generate_contract_reference.py`. Do not edit this file by hand.', '',
        'Check without writing: `python tools/generate_contract_reference.py --check`.', '',
        'This reference covers declared role/queue/task transitions, normalized runtime record fields,',
        'run state transitions and validated preset examples. Dynamic task/evidence checks still run',
        'in the domain services. The field tables are Python record contracts, not a complete YAML',
        'validation grammar: mapping keys supply IDs, manifests require `transport: acp`, and the',
        '[manifest guide](../concepts/codex-profiles.md) explains input configuration and constraints.', '',
        '## Queues', '']
    lines += table(['Queue', 'Kind', 'Owner', 'Writers'],
        [(name, row.get('kind'), row.get('owner'), row.get('writers', [])) for name, row in sorted(document['queues'].items())])
    lines += ['## Roles', '', 'Declarations below come directly from the normative schema; tokens are defined in its glossary.', '']
    for name, row in sorted(document['roles'].items()):
        lines += ['### ' + name, '', '```yaml', yaml.safe_dump(row, sort_keys=True, allow_unicode=False).rstrip(), '```', '']
    lines += ['## Task transitions', '',
              'Dynamic queue/owner selectors remain literal; the task policy resolves them against the current task and queue.', '']
    lines += table(['From', 'To', 'Role', 'Required validators'],
        [(row['from'], row['to'], row['by'], row.get('requires', [])) for row in document['transitions']])
    lines += ['## Declared daemon operations', '', 'These operations belong to SYSTEM, not to an agent role.', '',
        '```yaml', yaml.safe_dump(document['system_transitions'], sort_keys=True).rstrip(), '```', '',
        '## Run state transitions', '']
    lines += table(['State', 'Permitted next states'],
                   [(name, sorted(targets)) for name, targets in sorted(store.TRANSITIONS.items())])
    lines += ['Terminal states: ' + ', '.join(f'`{name}`' for name in sorted(store.TERMINAL)) + '.', '',
              '## Normalized runtime fields', '',
              'Required means the Python record has no default. Defaults use JSON notation (tuples become arrays); null and empty collections are distinct.', '']
    for record in (config.AgentManifest, config.RoleBinding, config.CommandDefinition,
                   account_limits.AccountLimitError, config.StandDeploymentPolicy,
                   config.ExecutionConfig, store.TaskRevision, store.ResultEnvelope):
        lines += ['### ' + record.__name__, '']
        rows = []
        for field in fields(record):
            default = 'required' if field.default is MISSING else json.dumps(field.default, ensure_ascii=True)
            type_name = field.type.__name__ if isinstance(field.type, type) else str(field.type)
            rows.append((field.name, type_name, default))
        lines += table(['Field', 'Python type', 'Default'], rows)
    lines += ['## Validated preset examples', '',
        'Executable and version values are placeholders. No harness is launched by generation.',
        'Stand profiles and validation commands need separate project configuration.', '']
    for name, example in examples.items():
        lines += ['### ' + name, '', '```yaml', yaml.safe_dump(example, sort_keys=True).rstrip(), '```', '']
    lines += ['## Source fingerprints', '',
        'The check also detects changes to validators and controllers referenced by these declarations.', '']
    lines += table(['Source', 'SHA-256'], sorted(sources.items()))
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path, default=OUTPUT)
    args = parser.parse_args()
    try:
        generated = render()
        if args.check:
            if not args.output.is_file() or args.output.read_text() != generated:
                parser.exit(1, 'contract reference is missing or stale; run python tools/generate_contract_reference.py\n')
        else:
            args.output.write_text(generated)
    except (ValueError, OSError) as exc:
        parser.exit(1, str(exc) + '\n')


if __name__ == '__main__':
    main()
